print("a      a^2     a^3")
a = 1
b = 2
c = 3
d = 4
print(f"{a}      {a**2}      {a**3}")
print(f"{b}      {b**2}      {b**3}")
print(f"{c}      {c**2}      {c**3}")
print(f"{d}      {d**2}      {d**3}")